# Generated by Django 2.2.6 on 2020-02-12 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(help_text='Where you are located.', max_length=100)),
                ('slug', models.CharField(blank=True, editable=False, help_text='Unique URL path to access this person. Generated by the system.', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The date and time this request was created. Automatically generated when the model saves.')),
                ('modified', models.DateTimeField(auto_now=True, help_text='The date and time this request was updated. Automatically generated when the model updates.')),
                ('author', models.ForeignKey(help_text='Name of passenger.', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.CharField(help_text='What you are driving.', max_length=50)),
                ('slug', models.CharField(blank=True, editable=False, help_text='Unique URL path to access this person. Generated by the system.', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The date and time availability was created. Automatically generated when the model saves.')),
                ('modified', models.DateTimeField(auto_now=True, help_text='The date and time availability was updated. Automatically generated when the model updates.')),
                ('author', models.ForeignKey(help_text='Name of driver.', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
