# Generated by Django 3.0.3 on 2020-02-26 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200226_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_passenger',
            field=models.BooleanField(default=True),
        ),
    ]
